---
# ===================================================================
# ملف إعدادات Logstash الرئيسي
# ===================================================================
# هذا الملف يحتوي على الإعدادات الأساسية لـ Logstash
# المرجع: https://github.com/elastic/logstash/blob/main/docker/data/logstash/config/logstash-full.yml
# ===================================================================

# ===================================================================
# إعدادات API HTTP (HTTP API Settings)
# ===================================================================
# عنوان IP الذي يستمع إليه Logstash API
# 0.0.0.0 يعني الاستماع على جميع واجهات الشبكة
# يستخدم للمراقبة والإدارة عبر المنفذ 9600
api.http.host: 0.0.0.0

# ===================================================================
# إعدادات العقدة (Node Settings)
# ===================================================================
# اسم عقدة Logstash - يظهر في السجلات والمراقبة
# مفيد عند تشغيل عدة عقد Logstash
node.name: bms-logstash-node

# ===================================================================
# إعدادات الأداء المحسنة (Performance Settings)
# ===================================================================
# عدد العمال للمعالجة المتوازية (50% من أنوية المعالج)
pipeline.workers: 4

# حجم الدفعة لمعالجة أكثر كفاءة
pipeline.batch.size: 1000

# تأخير الدفعة بالميلي ثانية
pipeline.batch.delay: 50

# ===================================================================
# إعدادات الطابور المستمر (Persistent Queue Settings)
# ===================================================================
# نوع الطابور المستمر لحماية من فقدان البيانات
queue.type: persisted

# الحد الأقصى لحجم الطابور
queue.max_bytes: 2gb

# ===================================================================
# إعدادات المراقبة (Monitoring Settings)
# ===================================================================
# تفعيل المراقبة
monitoring.enabled: true

# عناوين Elasticsearch للمراقبة
monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
