# ===================================================================
# ملف إعدادات خطوط المعالجة في Logstash (Pipelines Configuration)
# ===================================================================
# هذا الملف يحدد خطوط المعالجة المختلفة التي يشغلها Logstash
# كل خط معالجة له معرف فريد ومسار ملف الإعدادات الخاص به
# ===================================================================

# ===================================================================
# خط المعالجة الرئيسي (Main Pipeline)
# ===================================================================
# خط المعالجة الافتراضي للبيانات العامة
- pipeline.id: main                                    # معرف خط المعالجة الرئيسي
  path.config: "/usr/share/logstash/pipeline/logstash.conf"  # مسار ملف إعدادات المعالجة
  
# ===================================================================
# خط معالجة بيانات MySQL للكتب (MySQL Books Pipeline)
# ===================================================================
# خط معالجة مخصص لمعالجة بيانات الكتب من قاعدة بيانات MySQL
- pipeline.id: mysql-books                             # معرف خط معالجة MySQL
  path.config: "/usr/share/logstash/pipeline/mysql-books.conf"  # مسار ملف إعدادات معالجة MySQL
